### ISSUE TITLE
FInstancedStruct doesn't work

### ISSUE THREAD

**Issue by wickerman123** [nicholas477/JsonSerialization#1]
Hi,

Thanks for the awesome plugin.

The new _FInstancedStruct_ from the _StructUtils_ plugin does not work when converting an object containing Instanced Structs to JSON. I assume that's expected but as _FInstancedStruct_ is supposed to support serialisation, it'd be nice if it could work with the _Object to JSON_ node.

![notepad++_u9FexYM8Yj](https://github.com/nicholas477/JsonSerialization/assets/5807444/13edc0b0-1614-4c89-b8f4-4fc2fba29370)

**Comment by nicholas477** [comment]
Working on support for instanced structs rn. 

Do you have a discord? It would be easier for me to get in contact with you that way. My discord username is: epicgameguy

**Comment by wickerman123** [comment]
> Working on support for instanced structs rn.
> 
> Do you have a discord? It would be easier for me to get in contact with you that way. My discord username is: epicgameguy

Glad to hear it, struct inheritance opens a lot of doors for JSON formatting too. I've sent you a friend request - username is the same as here.

**Comment by nicholas477** [comment]
Fixed by version 1.1
